//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoSharing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creators()
        {
            this.Uploads = new HashSet<Uploads>();
        }
    
        public decimal creator_id { get; set; }
        public string creator_name { get; set; }
        public string creator_email { get; set; }
        public Nullable<System.DateTime> creator_birth_date { get; set; }
        public Nullable<decimal> creator_premium { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploads> Uploads { get; set; }
    }
}
