//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoSharing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uploads
    {
        public decimal upload_id { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public decimal video_id { get; set; }
        public decimal creator_id { get; set; }
    
        public virtual Creators Creators { get; set; }
        public virtual Videos Videos { get; set; }
    }
}
