//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoSharing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videos()
        {
            this.Uploads = new HashSet<Uploads>();
        }
    
        public decimal video_id { get; set; }
        public string video_title { get; set; }
        public string video_description { get; set; }
        public decimal creator_id { get; set; }
        public decimal category_id { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Creators Creators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploads> Uploads { get; set; }
    }
}
