/*CREATE TABLES*/
CREATE TABLE CREATORS(
	CREATOR_ID NUMERIC(20),
	CREATOR_NAME VARCHAR(30),
	CREATOR_EMAIL VARCHAR(70),
	CREATOR_BIRTH_DATE DATETIME,
	CREATOR_PREMIUM NUMERIC(1),
	CONSTRAINT CREATORS_PK PRIMARY KEY(CREATOR_ID)
);

CREATE TABLE CATEGORIES(
	CATEGORY_ID NUMERIC(20),
	CATEGORY_NAME VARCHAR(30),
	CATEGORY_ADULT NUMERIC(1),
	CONSTRAINT CATEGORIES_PK PRIMARY KEY(CATEGORY_ID)
);

CREATE TABLE VIDEOS(
	VIDEO_ID NUMERIC(20),
	VIDEO_TITLE VARCHAR(255) NOT NULL,
	VIDEO_DESCRIPTION VARCHAR(255),
	VIDEO_VIEWS NUMERIC(10),
	CATEGORY_ID NUMERIC(20) NOT NULL,
	CONSTRAINT VIDEOS_PK PRIMARY KEY(VIDEO_ID),
	CONSTRAINT CATEGORY_VID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE UPLOADS(
	UPLOAD_ID NUMERIC(20),
	UPLOAD_DATE DATETIME,
	VIDEO_ID NUMERIC(20) NOT NULL,
	CREATOR_ID NUMERIC(20) NOT NULL,
	CONSTRAINT UPLOADS_PK PRIMARY KEY(UPLOAD_ID),
	CONSTRAINT VIDEO_UPL_FK FOREIGN KEY(VIDEO_ID) REFERENCES VIDEOS(VIDEO_ID),
	CONSTRAINT CREATOR_UPL_FK FOREIGN KEY(CREATOR_ID) REFERENCES CREATORS(CREATOR_ID)
);